name: StyloView
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^3.3.1
  cupertino_icons: ^0.1.2
  xml: ^3.4.1
  dart_amqp: ^0.1.2
  sqflite: ^1.1.6+4
  path_provider: ^1.4.0
  utf: ^0.9.0+5
  crypto: ^2.1.3
  provider: ^3.1.0
  uuid: ^2.0.2
  flutter_bloc: ^0.21.0
  http: ^0.12.0+2
  sembast: ^2.1.0+1
  archive: ^2.0.10
  progress_dialog: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/PPY_IMAGE1.png